//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shfyovshofyshv
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ тапочек.
    /// </summary>
    // *** Start programmer edit section *** (ЗаказТапочек CustomAttributes)

    // *** End programmer edit section *** (ЗаказТапочек CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ тапочек")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказТапочекE", new string[] {
            "Комментарий as \'Комментарий\'"})]
    public class ЗаказТапочек : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Shfyovshofyshv.Тапочки fТапочки;
        
        private IIS.Shfyovshofyshv.Запись fЗапись;
        
        // *** Start programmer edit section *** (ЗаказТапочек CustomMembers)

        // *** End programmer edit section *** (ЗаказТапочек CustomMembers)

        
        /// <summary>
        /// Заказ тапочек.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказТапочек.Тапочки CustomAttributes)

        // *** End programmer edit section *** (ЗаказТапочек.Тапочки CustomAttributes)
        [PropertyStorage(new string[] {
                "Тапочки"})]
        [NotNull()]
        public virtual IIS.Shfyovshofyshv.Тапочки Тапочки
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказТапочек.Тапочки Get start)

                // *** End programmer edit section *** (ЗаказТапочек.Тапочки Get start)
                IIS.Shfyovshofyshv.Тапочки result = this.fТапочки;
                // *** Start programmer edit section *** (ЗаказТапочек.Тапочки Get end)

                // *** End programmer edit section *** (ЗаказТапочек.Тапочки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказТапочек.Тапочки Set start)

                // *** End programmer edit section *** (ЗаказТапочек.Тапочки Set start)
                this.fТапочки = value;
                // *** Start programmer edit section *** (ЗаказТапочек.Тапочки Set end)

                // *** End programmer edit section *** (ЗаказТапочек.Тапочки Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Shfyovshofyshv.Запись.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказТапочек.Запись CustomAttributes)

        // *** End programmer edit section *** (ЗаказТапочек.Запись CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Запись"})]
        public virtual IIS.Shfyovshofyshv.Запись Запись
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказТапочек.Запись Get start)

                // *** End programmer edit section *** (ЗаказТапочек.Запись Get start)
                IIS.Shfyovshofyshv.Запись result = this.fЗапись;
                // *** Start programmer edit section *** (ЗаказТапочек.Запись Get end)

                // *** End programmer edit section *** (ЗаказТапочек.Запись Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказТапочек.Запись Set start)

                // *** End programmer edit section *** (ЗаказТапочек.Запись Set start)
                this.fЗапись = value;
                // *** Start programmer edit section *** (ЗаказТапочек.Запись Set end)

                // *** End programmer edit section *** (ЗаказТапочек.Запись Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказТапочекE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказТапочекE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказТапочекE", typeof(IIS.Shfyovshofyshv.ЗаказТапочек));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаказТапочек.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаказТапочек CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаказТапочек CustomAttributes)
    public class DetailArrayOfЗаказТапочек : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Shfyovshofyshv.DetailArrayOfЗаказТапочек members)

        // *** End programmer edit section *** (IIS.Shfyovshofyshv.DetailArrayOfЗаказТапочек members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаказТапочек by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаказТапочек.
        /// </summary>
        public DetailArrayOfЗаказТапочек(IIS.Shfyovshofyshv.Запись fЗапись) : 
                base(typeof(ЗаказТапочек), ((ICSSoft.STORMNET.DataObject)(fЗапись)))
        {
        }
        
        public IIS.Shfyovshofyshv.ЗаказТапочек this[int index]
        {
            get
            {
                return ((IIS.Shfyovshofyshv.ЗаказТапочек)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Shfyovshofyshv.ЗаказТапочек dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
