//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shfyovshofyshv
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (Пациент CustomAttributes)

    // *** End programmer edit section *** (Пациент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентыE", new string[] {
            "КодКлиента as \'Код клиента\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерТелефона as \'Номер телефона\'"})]
    [View("КлиентыL", new string[] {
            "КодКлиента as \'Код клиента\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерТелефона as \'Номер телефона\'"})]
    [View("ПациентE", new string[] {
            "КодКлиента as \'Код клиента\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерТелефона as \'Номер телефона\'"})]
    [View("ПациентL", new string[] {
            "КодКлиента as \'Код клиента\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерТелефона as \'Номер телефона\'"})]
    public class Пациент : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодКлиента;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private int fНомерТелефона;
        
        // *** Start programmer edit section *** (Пациент CustomMembers)

        // *** End programmer edit section *** (Пациент CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Пациент.Имя CustomAttributes)

        // *** End programmer edit section *** (Пациент.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Пациент.Имя Get start)

                // *** End programmer edit section *** (Пациент.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Пациент.Имя Get end)

                // *** End programmer edit section *** (Пациент.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пациент.Имя Set start)

                // *** End programmer edit section *** (Пациент.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Пациент.Имя Set end)

                // *** End programmer edit section *** (Пациент.Имя Set end)
            }
        }
        
        /// <summary>
        /// КодКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Пациент.КодКлиента CustomAttributes)

        // *** End programmer edit section *** (Пациент.КодКлиента CustomAttributes)
        public virtual int КодКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Пациент.КодКлиента Get start)

                // *** End programmer edit section *** (Пациент.КодКлиента Get start)
                int result = this.fКодКлиента;
                // *** Start programmer edit section *** (Пациент.КодКлиента Get end)

                // *** End programmer edit section *** (Пациент.КодКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пациент.КодКлиента Set start)

                // *** End programmer edit section *** (Пациент.КодКлиента Set start)
                this.fКодКлиента = value;
                // *** Start programmer edit section *** (Пациент.КодКлиента Set end)

                // *** End programmer edit section *** (Пациент.КодКлиента Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (Пациент.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (Пациент.НомерТелефона CustomAttributes)
        public virtual int НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (Пациент.НомерТелефона Get start)

                // *** End programmer edit section *** (Пациент.НомерТелефона Get start)
                int result = this.fНомерТелефона;
                // *** Start programmer edit section *** (Пациент.НомерТелефона Get end)

                // *** End programmer edit section *** (Пациент.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пациент.НомерТелефона Set start)

                // *** End programmer edit section *** (Пациент.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (Пациент.НомерТелефона Set end)

                // *** End programmer edit section *** (Пациент.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Пациент.Отчество CustomAttributes)

        // *** End programmer edit section *** (Пациент.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Пациент.Отчество Get start)

                // *** End programmer edit section *** (Пациент.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Пациент.Отчество Get end)

                // *** End programmer edit section *** (Пациент.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пациент.Отчество Set start)

                // *** End programmer edit section *** (Пациент.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Пациент.Отчество Set end)

                // *** End programmer edit section *** (Пациент.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Пациент.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Пациент.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Пациент.Фамилия Get start)

                // *** End programmer edit section *** (Пациент.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Пациент.Фамилия Get end)

                // *** End programmer edit section *** (Пациент.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пациент.Фамилия Set start)

                // *** End programmer edit section *** (Пациент.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Пациент.Фамилия Set end)

                // *** End programmer edit section *** (Пациент.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыE", typeof(IIS.Shfyovshofyshv.Пациент));
                }
            }
            
            /// <summary>
            /// "КлиентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыL", typeof(IIS.Shfyovshofyshv.Пациент));
                }
            }
            
            /// <summary>
            /// "ПациентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПациентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПациентE", typeof(IIS.Shfyovshofyshv.Пациент));
                }
            }
            
            /// <summary>
            /// "ПациентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПациентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПациентL", typeof(IIS.Shfyovshofyshv.Пациент));
                }
            }
        }
    }
}
