//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shfyovshofyshv
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сланцы.
    /// </summary>
    // *** Start programmer edit section *** (Сланцы CustomAttributes)

    // *** End programmer edit section *** (Сланцы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СланцыE", new string[] {
            "КодСланцев as \'Код сланцев\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    [AssociatedDetailViewAttribute("СланцыE", "ХарСланцев", "ХарСланцевE", true, "", "Хар сланцев", true, new string[] {
            ""})]
    [View("СланцыL", new string[] {
            "КодСланцев as \'Код сланцев\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    public class Сланцы : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодСланцев;
        
        private string fНаименование;
        
        private double fСтоимость;
        
        private IIS.Shfyovshofyshv.DetailArrayOfХарСланцев fХарСланцев;
        
        // *** Start programmer edit section *** (Сланцы CustomMembers)

        // *** End programmer edit section *** (Сланцы CustomMembers)

        
        /// <summary>
        /// КодСланцев.
        /// </summary>
        // *** Start programmer edit section *** (Сланцы.КодСланцев CustomAttributes)

        // *** End programmer edit section *** (Сланцы.КодСланцев CustomAttributes)
        public virtual int КодСланцев
        {
            get
            {
                // *** Start programmer edit section *** (Сланцы.КодСланцев Get start)

                // *** End programmer edit section *** (Сланцы.КодСланцев Get start)
                int result = this.fКодСланцев;
                // *** Start programmer edit section *** (Сланцы.КодСланцев Get end)

                // *** End programmer edit section *** (Сланцы.КодСланцев Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сланцы.КодСланцев Set start)

                // *** End programmer edit section *** (Сланцы.КодСланцев Set start)
                this.fКодСланцев = value;
                // *** Start programmer edit section *** (Сланцы.КодСланцев Set end)

                // *** End programmer edit section *** (Сланцы.КодСланцев Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Сланцы.Наименование CustomAttributes)

        // *** End programmer edit section *** (Сланцы.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Сланцы.Наименование Get start)

                // *** End programmer edit section *** (Сланцы.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Сланцы.Наименование Get end)

                // *** End programmer edit section *** (Сланцы.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сланцы.Наименование Set start)

                // *** End programmer edit section *** (Сланцы.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Сланцы.Наименование Set end)

                // *** End programmer edit section *** (Сланцы.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Сланцы.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Сланцы.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Сланцы.Стоимость Get start)

                // *** End programmer edit section *** (Сланцы.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (Сланцы.Стоимость Get end)

                // *** End programmer edit section *** (Сланцы.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сланцы.Стоимость Set start)

                // *** End programmer edit section *** (Сланцы.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Сланцы.Стоимость Set end)

                // *** End programmer edit section *** (Сланцы.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Сланцы.
        /// </summary>
        // *** Start programmer edit section *** (Сланцы.ХарСланцев CustomAttributes)

        // *** End programmer edit section *** (Сланцы.ХарСланцев CustomAttributes)
        public virtual IIS.Shfyovshofyshv.DetailArrayOfХарСланцев ХарСланцев
        {
            get
            {
                // *** Start programmer edit section *** (Сланцы.ХарСланцев Get start)

                // *** End programmer edit section *** (Сланцы.ХарСланцев Get start)
                if ((this.fХарСланцев == null))
                {
                    this.fХарСланцев = new IIS.Shfyovshofyshv.DetailArrayOfХарСланцев(this);
                }
                IIS.Shfyovshofyshv.DetailArrayOfХарСланцев result = this.fХарСланцев;
                // *** Start programmer edit section *** (Сланцы.ХарСланцев Get end)

                // *** End programmer edit section *** (Сланцы.ХарСланцев Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сланцы.ХарСланцев Set start)

                // *** End programmer edit section *** (Сланцы.ХарСланцев Set start)
                this.fХарСланцев = value;
                // *** Start programmer edit section *** (Сланцы.ХарСланцев Set end)

                // *** End programmer edit section *** (Сланцы.ХарСланцев Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СланцыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СланцыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СланцыE", typeof(IIS.Shfyovshofyshv.Сланцы));
                }
            }
            
            /// <summary>
            /// "СланцыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СланцыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СланцыL", typeof(IIS.Shfyovshofyshv.Сланцы));
                }
            }
        }
    }
}
