//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shfyovshofyshv
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тапочки.
    /// </summary>
    // *** Start programmer edit section *** (Тапочки CustomAttributes)

    // *** End programmer edit section *** (Тапочки CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТапочкиE", new string[] {
            "КодТапочек as \'Код тапочек\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    [AssociatedDetailViewAttribute("ТапочкиE", "ХарТапочек", "ХарТапочекE", true, "", "Хар тапочек", true, new string[] {
            ""})]
    [View("ТапочкиL", new string[] {
            "КодТапочек as \'Код тапочек\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    public class Тапочки : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодТапочек;
        
        private string fНаименование;
        
        private double fСтоимость;
        
        private IIS.Shfyovshofyshv.DetailArrayOfХарТапочек fХарТапочек;
        
        // *** Start programmer edit section *** (Тапочки CustomMembers)

        // *** End programmer edit section *** (Тапочки CustomMembers)

        
        /// <summary>
        /// КодТапочек.
        /// </summary>
        // *** Start programmer edit section *** (Тапочки.КодТапочек CustomAttributes)

        // *** End programmer edit section *** (Тапочки.КодТапочек CustomAttributes)
        public virtual int КодТапочек
        {
            get
            {
                // *** Start programmer edit section *** (Тапочки.КодТапочек Get start)

                // *** End programmer edit section *** (Тапочки.КодТапочек Get start)
                int result = this.fКодТапочек;
                // *** Start programmer edit section *** (Тапочки.КодТапочек Get end)

                // *** End programmer edit section *** (Тапочки.КодТапочек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тапочки.КодТапочек Set start)

                // *** End programmer edit section *** (Тапочки.КодТапочек Set start)
                this.fКодТапочек = value;
                // *** Start programmer edit section *** (Тапочки.КодТапочек Set end)

                // *** End programmer edit section *** (Тапочки.КодТапочек Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Тапочки.Наименование CustomAttributes)

        // *** End programmer edit section *** (Тапочки.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Тапочки.Наименование Get start)

                // *** End programmer edit section *** (Тапочки.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Тапочки.Наименование Get end)

                // *** End programmer edit section *** (Тапочки.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тапочки.Наименование Set start)

                // *** End programmer edit section *** (Тапочки.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Тапочки.Наименование Set end)

                // *** End programmer edit section *** (Тапочки.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Тапочки.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Тапочки.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Тапочки.Стоимость Get start)

                // *** End programmer edit section *** (Тапочки.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (Тапочки.Стоимость Get end)

                // *** End programmer edit section *** (Тапочки.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тапочки.Стоимость Set start)

                // *** End programmer edit section *** (Тапочки.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Тапочки.Стоимость Set end)

                // *** End programmer edit section *** (Тапочки.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Тапочки.
        /// </summary>
        // *** Start programmer edit section *** (Тапочки.ХарТапочек CustomAttributes)

        // *** End programmer edit section *** (Тапочки.ХарТапочек CustomAttributes)
        public virtual IIS.Shfyovshofyshv.DetailArrayOfХарТапочек ХарТапочек
        {
            get
            {
                // *** Start programmer edit section *** (Тапочки.ХарТапочек Get start)

                // *** End programmer edit section *** (Тапочки.ХарТапочек Get start)
                if ((this.fХарТапочек == null))
                {
                    this.fХарТапочек = new IIS.Shfyovshofyshv.DetailArrayOfХарТапочек(this);
                }
                IIS.Shfyovshofyshv.DetailArrayOfХарТапочек result = this.fХарТапочек;
                // *** Start programmer edit section *** (Тапочки.ХарТапочек Get end)

                // *** End programmer edit section *** (Тапочки.ХарТапочек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тапочки.ХарТапочек Set start)

                // *** End programmer edit section *** (Тапочки.ХарТапочек Set start)
                this.fХарТапочек = value;
                // *** Start programmer edit section *** (Тапочки.ХарТапочек Set end)

                // *** End programmer edit section *** (Тапочки.ХарТапочек Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТапочкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТапочкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТапочкиE", typeof(IIS.Shfyovshofyshv.Тапочки));
                }
            }
            
            /// <summary>
            /// "ТапочкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТапочкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТапочкиL", typeof(IIS.Shfyovshofyshv.Тапочки));
                }
            }
        }
    }
}
