//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shfyovshofyshv
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Хар тапочек.
    /// </summary>
    // *** Start programmer edit section *** (ХарТапочек CustomAttributes)

    // *** End programmer edit section *** (ХарТапочек CustomAttributes)
    [AutoAltered()]
    [Caption("Хар тапочек")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ХарТапочекE", new string[] {
            "Количество as \'Количество\'",
            "Размер as \'Размер\'"})]
    public class ХарТапочек : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private int fРазмер;
        
        private IIS.Shfyovshofyshv.Категория fКатегория;
        
        private IIS.Shfyovshofyshv.Тапочки fТапочки;
        
        // *** Start programmer edit section *** (ХарТапочек CustomMembers)

        // *** End programmer edit section *** (ХарТапочек CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ХарТапочек.Количество CustomAttributes)

        // *** End programmer edit section *** (ХарТапочек.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ХарТапочек.Количество Get start)

                // *** End programmer edit section *** (ХарТапочек.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ХарТапочек.Количество Get end)

                // *** End programmer edit section *** (ХарТапочек.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХарТапочек.Количество Set start)

                // *** End programmer edit section *** (ХарТапочек.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ХарТапочек.Количество Set end)

                // *** End programmer edit section *** (ХарТапочек.Количество Set end)
            }
        }
        
        /// <summary>
        /// Размер.
        /// </summary>
        // *** Start programmer edit section *** (ХарТапочек.Размер CustomAttributes)

        // *** End programmer edit section *** (ХарТапочек.Размер CustomAttributes)
        public virtual int Размер
        {
            get
            {
                // *** Start programmer edit section *** (ХарТапочек.Размер Get start)

                // *** End programmer edit section *** (ХарТапочек.Размер Get start)
                int result = this.fРазмер;
                // *** Start programmer edit section *** (ХарТапочек.Размер Get end)

                // *** End programmer edit section *** (ХарТапочек.Размер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХарТапочек.Размер Set start)

                // *** End programmer edit section *** (ХарТапочек.Размер Set start)
                this.fРазмер = value;
                // *** Start programmer edit section *** (ХарТапочек.Размер Set end)

                // *** End programmer edit section *** (ХарТапочек.Размер Set end)
            }
        }
        
        /// <summary>
        /// Хар тапочек.
        /// </summary>
        // *** Start programmer edit section *** (ХарТапочек.Категория CustomAttributes)

        // *** End programmer edit section *** (ХарТапочек.Категория CustomAttributes)
        [PropertyStorage(new string[] {
                "Категория"})]
        [NotNull()]
        public virtual IIS.Shfyovshofyshv.Категория Категория
        {
            get
            {
                // *** Start programmer edit section *** (ХарТапочек.Категория Get start)

                // *** End programmer edit section *** (ХарТапочек.Категория Get start)
                IIS.Shfyovshofyshv.Категория result = this.fКатегория;
                // *** Start programmer edit section *** (ХарТапочек.Категория Get end)

                // *** End programmer edit section *** (ХарТапочек.Категория Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХарТапочек.Категория Set start)

                // *** End programmer edit section *** (ХарТапочек.Категория Set start)
                this.fКатегория = value;
                // *** Start programmer edit section *** (ХарТапочек.Категория Set end)

                // *** End programmer edit section *** (ХарТапочек.Категория Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Shfyovshofyshv.Тапочки.
        /// </summary>
        // *** Start programmer edit section *** (ХарТапочек.Тапочки CustomAttributes)

        // *** End programmer edit section *** (ХарТапочек.Тапочки CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Тапочки"})]
        public virtual IIS.Shfyovshofyshv.Тапочки Тапочки
        {
            get
            {
                // *** Start programmer edit section *** (ХарТапочек.Тапочки Get start)

                // *** End programmer edit section *** (ХарТапочек.Тапочки Get start)
                IIS.Shfyovshofyshv.Тапочки result = this.fТапочки;
                // *** Start programmer edit section *** (ХарТапочек.Тапочки Get end)

                // *** End programmer edit section *** (ХарТапочек.Тапочки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХарТапочек.Тапочки Set start)

                // *** End programmer edit section *** (ХарТапочек.Тапочки Set start)
                this.fТапочки = value;
                // *** Start programmer edit section *** (ХарТапочек.Тапочки Set end)

                // *** End programmer edit section *** (ХарТапочек.Тапочки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ХарТапочекE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ХарТапочекE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ХарТапочекE", typeof(IIS.Shfyovshofyshv.ХарТапочек));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ХарТапочек.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfХарТапочек CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfХарТапочек CustomAttributes)
    public class DetailArrayOfХарТапочек : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Shfyovshofyshv.DetailArrayOfХарТапочек members)

        // *** End programmer edit section *** (IIS.Shfyovshofyshv.DetailArrayOfХарТапочек members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ХарТапочек by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ХарТапочек.
        /// </summary>
        public DetailArrayOfХарТапочек(IIS.Shfyovshofyshv.Тапочки fТапочки) : 
                base(typeof(ХарТапочек), ((ICSSoft.STORMNET.DataObject)(fТапочки)))
        {
        }
        
        public IIS.Shfyovshofyshv.ХарТапочек this[int index]
        {
            get
            {
                return ((IIS.Shfyovshofyshv.ХарТапочек)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Shfyovshofyshv.ХарТапочек dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
