//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shfyovshofyshv
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Хар сланцев.
    /// </summary>
    // *** Start programmer edit section *** (ХарСланцев CustomAttributes)

    // *** End programmer edit section *** (ХарСланцев CustomAttributes)
    [AutoAltered()]
    [Caption("Хар сланцев")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ХарСланцевE", new string[] {
            "Количество as \'Количество\'",
            "Размер as \'Размер\'"})]
    public class ХарСланцев : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private int fРазмер;
        
        private IIS.Shfyovshofyshv.Категория fКатегория;
        
        private IIS.Shfyovshofyshv.Сланцы fСланцы;
        
        // *** Start programmer edit section *** (ХарСланцев CustomMembers)

        // *** End programmer edit section *** (ХарСланцев CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ХарСланцев.Количество CustomAttributes)

        // *** End programmer edit section *** (ХарСланцев.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ХарСланцев.Количество Get start)

                // *** End programmer edit section *** (ХарСланцев.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ХарСланцев.Количество Get end)

                // *** End programmer edit section *** (ХарСланцев.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХарСланцев.Количество Set start)

                // *** End programmer edit section *** (ХарСланцев.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ХарСланцев.Количество Set end)

                // *** End programmer edit section *** (ХарСланцев.Количество Set end)
            }
        }
        
        /// <summary>
        /// Размер.
        /// </summary>
        // *** Start programmer edit section *** (ХарСланцев.Размер CustomAttributes)

        // *** End programmer edit section *** (ХарСланцев.Размер CustomAttributes)
        public virtual int Размер
        {
            get
            {
                // *** Start programmer edit section *** (ХарСланцев.Размер Get start)

                // *** End programmer edit section *** (ХарСланцев.Размер Get start)
                int result = this.fРазмер;
                // *** Start programmer edit section *** (ХарСланцев.Размер Get end)

                // *** End programmer edit section *** (ХарСланцев.Размер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХарСланцев.Размер Set start)

                // *** End programmer edit section *** (ХарСланцев.Размер Set start)
                this.fРазмер = value;
                // *** Start programmer edit section *** (ХарСланцев.Размер Set end)

                // *** End programmer edit section *** (ХарСланцев.Размер Set end)
            }
        }
        
        /// <summary>
        /// Хар сланцев.
        /// </summary>
        // *** Start programmer edit section *** (ХарСланцев.Категория CustomAttributes)

        // *** End programmer edit section *** (ХарСланцев.Категория CustomAttributes)
        [PropertyStorage(new string[] {
                "Категория"})]
        [NotNull()]
        public virtual IIS.Shfyovshofyshv.Категория Категория
        {
            get
            {
                // *** Start programmer edit section *** (ХарСланцев.Категория Get start)

                // *** End programmer edit section *** (ХарСланцев.Категория Get start)
                IIS.Shfyovshofyshv.Категория result = this.fКатегория;
                // *** Start programmer edit section *** (ХарСланцев.Категория Get end)

                // *** End programmer edit section *** (ХарСланцев.Категория Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХарСланцев.Категория Set start)

                // *** End programmer edit section *** (ХарСланцев.Категория Set start)
                this.fКатегория = value;
                // *** Start programmer edit section *** (ХарСланцев.Категория Set end)

                // *** End programmer edit section *** (ХарСланцев.Категория Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Shfyovshofyshv.Сланцы.
        /// </summary>
        // *** Start programmer edit section *** (ХарСланцев.Сланцы CustomAttributes)

        // *** End programmer edit section *** (ХарСланцев.Сланцы CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Сланцы"})]
        public virtual IIS.Shfyovshofyshv.Сланцы Сланцы
        {
            get
            {
                // *** Start programmer edit section *** (ХарСланцев.Сланцы Get start)

                // *** End programmer edit section *** (ХарСланцев.Сланцы Get start)
                IIS.Shfyovshofyshv.Сланцы result = this.fСланцы;
                // *** Start programmer edit section *** (ХарСланцев.Сланцы Get end)

                // *** End programmer edit section *** (ХарСланцев.Сланцы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ХарСланцев.Сланцы Set start)

                // *** End programmer edit section *** (ХарСланцев.Сланцы Set start)
                this.fСланцы = value;
                // *** Start programmer edit section *** (ХарСланцев.Сланцы Set end)

                // *** End programmer edit section *** (ХарСланцев.Сланцы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ХарСланцевE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ХарСланцевE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ХарСланцевE", typeof(IIS.Shfyovshofyshv.ХарСланцев));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ХарСланцев.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfХарСланцев CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfХарСланцев CustomAttributes)
    public class DetailArrayOfХарСланцев : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Shfyovshofyshv.DetailArrayOfХарСланцев members)

        // *** End programmer edit section *** (IIS.Shfyovshofyshv.DetailArrayOfХарСланцев members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ХарСланцев by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ХарСланцев.
        /// </summary>
        public DetailArrayOfХарСланцев(IIS.Shfyovshofyshv.Сланцы fСланцы) : 
                base(typeof(ХарСланцев), ((ICSSoft.STORMNET.DataObject)(fСланцы)))
        {
        }
        
        public IIS.Shfyovshofyshv.ХарСланцев this[int index]
        {
            get
            {
                return ((IIS.Shfyovshofyshv.ХарСланцев)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Shfyovshofyshv.ХарСланцев dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
